name: Run checks in main and release

on:
  pull_request:
    branches:
      - '*release*'
      - main
  merge_group:
    branches:
      - '*release*'
      - main

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v9
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --locked --group dev
      - name: Run linters
        run: uv run ruff check . && uv run ruff format --check . && uv run codespell src examples tests
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v9
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --locked --group dev --group docs
    - name: Run tests and coverage
      run: uv run pytest --cov=aind_data_schema --cov=tests --cov-report=term-missing --cov-fail-under=100
  verify_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version incremented
        run: |
          pkg_name=$(grep -P 'version = \{attr = .*\}' pyproject.toml | grep -oP '\w+.__version__')
          init_file="./src/${pkg_name//.__version__}/__init__.py"
          pkg_version=$(grep -Po '[0-9]+\.[0-9]+\.[0-9]+' "$init_file")
          latest_tag=$(git ls-remote --tags --refs --sort="v:refname" | tail -n1 | sed 's/.*\///')
          echo "Checking pkg_version v$pkg_version and latest_tag $latest_tag"
          if [ "$latest_tag" == "v$pkg_version" ]
          then
            exit 1
          fi
          echo "Versions are different"
