name: Run checks in main and release

on:
  push:
    branches:
      - '*release*'

jobs:
  bump_versions_and_update_schemas:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: 'schemas'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SERVICE_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: uv sync --locked --group dev
      - name: Bump schema versions
        run: |
          uv run python -m aind_data_schema.utils.schema_version_bump
          echo "Finished schema version bump"
      - name: Update schemas
        run: |
          rm -rf $OUTPUT_DIR
          uv run python -m aind_data_schema.utils.json_writer --output $OUTPUT_DIR
      - name: Create example schemas
        run: |
          cd examples
          for script in ./*.py; do
              uv run python "$script"
          done
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "bump schema version [skip actions]"
          add: '["src", "schemas", "examples"]'

  update_docs:
    needs: bump_versions_and_update_schemas
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SERVICE_TOKEN }}
          ref: ${{ github.ref }}
      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: uv sync --locked --group dev --group docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "updates diagrams [skip actions]"
          add: '["*.rst"]'
